# https://golangci-lint.run/usage/configuration/
version: "2"
run:
  timeout: 5m

issues:
  exclude-use-default: false

  # reviewdog limits max issues, so we don't do here.
  max-issues-per-linter: 0
  max-same-issues: 0
