# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: "cli"
    env:
      - CGO_ENABLED=0
    main: ./cli/go-prove/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/shogo82148/go-prove.version={{.Version}}
      - -X github.com/shogo82148/go-prove.commit={{.ShortCommit}}
checksum:
  name_template: "checksums.txt"
archives:
  - builds:
      - "cli"
    files:
      - CREDITS
      - LICENSE
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
