name: credits

on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - ".github/workflows/credits.yml"
  workflow_dispatch:

jobs:
  credits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - name: install gocredits
        run: go install github.com/Songmu/gocredits/cmd/gocredits@latest

      - name: Run gocredits
        run: make credits
      - name: commit and create a pull request
        uses: shogo82148/actions-commit-and-create-pr@b1322fe9da4037e9720e34ea221997cffcd3498d # v1.1.4
        with:
          commit-message: Update CREDITS
          title: Update CREDITS
