name: credits

on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - ".github/workflows/credits.yml"
  workflow_dispatch:

jobs:
  credits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
      - name: install gocredits
        run: go install github.com/Songmu/gocredits/cmd/gocredits@latest

      - name: Run gocredits
        run: make credits
      - name: commit and create a pull request
        uses: shogo82148/actions-commit-and-create-pr@b1322fe9da4037e9720e34ea221997cffcd3498d # v1.1.4
        with:
          commit-message: Update CREDITS
          title: Update CREDITS
