name: tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: generate GitHub App Token
        id: generate
        uses: shogo82148/actions-github-app-token@bbdb11feaf1f848a9e8f84cb1d10a8b97e4d9f5b # v1.3.3

      - name: Check out source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5.0.1
        with:
          token: ${{ steps.generate.outputs.token }}
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: .go-version

      - id: run-tagpr
        name: Run tagpr
        uses: Songmu/tagpr@2afc990a4a5a9a340665cc1a484c2102f7de332f # v1.21.0
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
