name: tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: generate GitHub App Token
        id: generate
        uses: shogo82148/actions-github-app-token@974a23b2c503ebde567cf6b78354bb6e2791d3b8 # v1.1.1

      - name: Check out source code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v5.0.1
        with:
          token: ${{ steps.generate.outputs.token }}
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - id: run-tagpr
        name: Run tagpr
        uses: Songmu/tagpr@84850af451fc53753c6685a3a6a2af7beef23607 # v1.18.2
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
